### ISSUE TITLE
Option to output to Pentaho stream field instead of file

### ISSUE THREAD

**Issue by chrissjacks** [cdeptula/AvroOutputPlugin#15]
Firstly, thanks for the great plugin!

It would be great if there was an option to send Avro Output to a Pentaho stream "field" instead of only to a file.  Is this possible to implement?

**Use case**: I want to send my Avro output to a message broker (a Kafka producer) which accepts the message in a field.

It looks like at present I will need to read the Avro output file back into a Pentaho field before sending that field to my Kafka Producer step.

Thanks!

Regards,

Chris

**Comment by cdeptula** [comment]
This is fixed in version 3.0 of the plugin, which should be released in early July.  In the mean time if you need this immediately, you can build the plugin from source.

**Comment by chrissjacks** [comment]
Awesome!  I will wait until the early July release.  Thanks!!!
