### ISSUE TITLE
Option to exclude schema in output

### ISSUE THREAD

**Issue by chrissjacks** [cdeptula/AvroOutputPlugin#16]
It looks as though this plugin includes the schema itself as a part of the serialised message content.

It would be great if we could choose to exclude the schema content!  Perhaps via a checkbox to include/exclude schema in output.

Regards,

Chris

**Comment by cdeptula** [comment]
The Avro file spec says that the schema used to write the file is always included as part of an Avro file.  I believe without the schema in the Avro file it would be impossible to read an Avro file.

Additionally, a  quick look through the Avro API also does not reveal a way to write an Avro file and not include a schema.  Therefore I do not believe this is possible.

If you can point me to documentation on someone writing Avro files without a schema and a use case for this, I might consider this.  But otherwise I do not think this is possible and will not do it.

**Comment by chrissjacks** [comment]
Hi Chris

Agreed, the recommendation from Apache is indeed to include the schema (https://avro.apache.org/docs/1.8.0/spec.html#Data+Serialization).

I am attempting to make Pentaho work with some Java appications that do not include the schema in their Avro serialisation (and therefore their apps do not expect to have the schema included).  I suspect the use case is...

Software developed for internal use by an organisaton or for use between parties who "know" what the schema will be every time do not need to include the schema with every message, and therefore can exclude it from messages to reduce load for every message transferred (may be significant with high message volume/frequency).

I recently had a look at https://streamsets.com/ too,  Their Kafka Consumer and Producer "steps" have Avro as a native serialisation setting, and within the Avro settings, when Consuming you can say whether the incoming avro file includes or excludes the schema.  And when producing to Kafka you can say whether or not to include the schema in the serialised message.

I understand that such use cases may be less common so imagine this functionality is not a high priority.  Thankyou very much for the reply to this issue post!


Cheers,

Chris

**Comment by cdeptula** [comment]
Version 3.0 with issue #15 allows you to output directly to a binary field instead of a file.  I think the best solution here is to have the Avro Output step output to the binary field and then use the Text File Output to output to a file without the schema if you want.

**Comment by chrissjacks** [comment]
Thanks Chris!
I'm actually looking to pass my binary field directly to a Kafka Producer step.  From a number of discussions with Java devs now, I believe that the Avro file spec to include the schema is only standard when producing to a file, not in a message streaming application (which is what I'm trying to use Pentaho for).
